### PR TITLE
[DOCS] Add downstream doc to upstream site

### PR DESCRIPTION
**Pull request by maryfrances01**
Add assemblies, modules, images, and custom CSS to move a downstream doc upstream.

## Description
Added assemblies, modules, images, and custom CSS in order to publish a downstream doc upstream.

## How Has This Been Tested?
Tested using GH Pages:
https://mhull-rhods-test.github.io/opendatahub.io/docs/working-on-data-science-projects.html

The following additional items need to be addressed:
- Working on Data Science Projects needs to be added to the side navigation. Currently, this document is only accessible via the link above.
- Figure out what to do with the TOC - should it be removed or added to the side navigation?
- I have addressed most of the formatting issues we encountered by using a custom CSS. One nice to have would be to provide font-based admonition and inline icons for call outs like NOTE and WARNING. Not sure if we can use icons from font-awesome for that. 

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by maryfrances01** [comment]
> 

@LaVLaS I removed the images that were for downstream docs only and they were also not needed for this particular assembly. Thanks!

**Comment by shalberd** [comment]
Surprised to see that RBAC for Data Science Projects and user-specific workbenches are not in the documentation. As it is currently, a Data Science Projects had notebook pods that are global for the project and not at all user-specific. Same for persistent storage, unsure about configmaps being global or user-specific on a Data Science Project. Have been in contact with Chris Chase. Unsure about whether user-specificity per Workbench in a project ha already been implemented upstream.

**Comment by cfchase** [comment]
Adding the TOC changes manually looks like: https://github.com/cfchase/opendatahub.io/commit/6bdf4853f693999052e328b2a362229c824c3f6a.

The title size was overflowing the width, so I shortened it.

Screenshot from 2023-01-31 20-13-04

**Comment by cfchase** [comment]
Original Titling is a bit overflowing

**Comment by cfchase** [comment]
Updated:

**Comment by maryfrances01** [comment]
> 

@LaVLaS added Chris's TOC changes

**Review by LaVLaS — APPROVED** [review]
LGTM

**Pull request merged**
