### PR TITLE
The dependencies are needed for the components

### PR DESCRIPTION
**Pull request by adelton**
## Description

The dependencies are needed for the components, not for the DataScienceCluster instance. Let's not complicate steps for setting up the DataScienceCluster instance with something which will only become relevant later.

Fixes https://github.com/opendatahub-io/opendatahub.io/issues/188.

## How Has This Been Tested?

Not tested.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by shalberd** [comment]
agreed. For example, if someone does not enable Pipelines or Model Serving, they don't need certain of those dependencies mention, yeah. Looks good to me.

**Comment by adelton** [comment]
Thanks @shalberd. What's the next process in this project? Do I push an agreed pull request directly, or does some other maintainer push, or something else?

**Comment by shalberd** [comment]
Hi @adelton a maintainer such as @Gkrumbach07 or @LaVLaS or @VaishnaviHire needs to make a lgtm comment.

**Comment by Gkrumbach07** [comment]
i see no issue with the changes
/lgtm

**Pull request merged**
