### PR TITLE
Release v1.11.0 / v2.3.0

### PR DESCRIPTION
**Pull request by zdtsw**
ref: https://github.com/opendatahub-io/opendatahub-community/issues/118

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@zdtsw do we know an ETA on this?

**Comment by zdtsw** [comment]
> @zdtsw do we know an ETA on this?

sorry for late reply, we had a bit problem to get the final ODH build done, but it is moving now. If all goes well, should be available in a couple of hours. to track https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3550

**Comment by zdtsw** [comment]
it has been released, so i just need someone can merge this PR :D

**Comment by Gkrumbach07** [comment]
lgtm

**Pull request merged**
